# Generated by Django 3.2.6 on 2021-09-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20210906_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=2, verbose_name='Текст комментария'),
        ),
    ]
