# Generated by Django 3.2.6 on 2021-09-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_alter_comments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='advert.PostCategory', to='advert.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.fan', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.CharField(default='Объявление пустое', max_length=2, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_post',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
