# Generated by Django 3.2.6 on 2021-09-08 10:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_auto_20210908_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
