# Generated by Django 3.2.3 on 2021-06-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_type',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Статья', 'Статья')], default='Новость', max_length=7),
        ),
    ]
