# Generated by Django 3.2.3 on 2021-06-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210627_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribing',
        ),
    ]
